services:
  # 1. The "All-in-One" Free Service (Web + Worker)
  - type: web
    name: zen-pdf-free
    env: python
    buildCommand: pip install -r requirements.txt
    # The Magic Command: Starts Celery in the background (--detach) then starts Flask
    startCommand: celery -A celery_worker.celery worker --loglevel=info --detach && gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: zen-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: zen-redis
          property: connectionString

  # 2. The Database (Free)
  - type: redis
    name: zen-redis
    plan: free
    ipAllowList: []